name: Tests (Push)
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test Main Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Up Deno
        uses: denoland/setup-deno@v1.1.4
        with:
          deno-version: v1.x
      - name: Lint
        run: deno lint
      - name: Check Formatting
        run: deno fmt --check